Models/Venda.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Dez.Models
{
    [Table("Vendas")]
    public class Venda
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = " ID: ")]
        public int id { get; set; }

        [Display(Name = "Farmacêutico")]
        public int IdFarmaceutico { get; set; }
        [ForeignKey("IdFarmaceutico")]
        public Farmaceutico farmaceutico { get; set; }

        [Display(Name = "Produto")]
        public int IdProduto { get; set; }
        [ForeignKey("IdProduto")]
        public Produto produto { get; set; }

        [Display(Name = "Cliente")]
        public int IdCliente { get; set; }
        [ForeignKey("IdCliente")]
        public Cliente cliente { get; set; }

        [Required(ErrorMessage = "Quantiade da venda obrigatório...")]
        [Range(1, 1000, ErrorMessage = "Esta quantia ultrapassa o nosso estoque")]
        [Display(Name = " quantidade ")]
        public int qntd { get; set; }

        [Required]
        [Display(Name = " total ")]
        public float total { get; set; }

    }
}

Controllers/ConsultaController.cs
using Dez.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dez.Controllers
{
    public class ConsultaController : Controller
    {
        private readonly Contexto contexto;

        public ConsultaController(Contexto context)
        {
            contexto = context;
        }

        public ActionResult VndC ()
        {
            var vend = contexto.Vendas.Include(v => v.cliente)
                                       .Include(v => v.farmaceutico)
                                       .Include(v => v.produto)
                                        .Where(o=>o.produto.nome=="Paracetamol");

            return View(vend);
        }
          

    }
}

Controllers/VendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dez.Models;
using Microsoft.AspNetCore.Authorization;

namespace Dez.Controllers
{
    [Authorize]
    public class VendasController : Controller
    {
        private readonly Contexto _context;

        public VendasController(Contexto context)
        {
            _context = context;
        }

        // GET: Vendas
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Vendas.Include(v => v.cliente).Include(v => v.farmaceutico).Include(v => v.produto);
            return View(await contexto.ToListAsync());
        }

        // GET: Vendas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.cliente)
                .Include(v => v.farmaceutico)
                .Include(v => v.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // GET: Vendas/Create
        public IActionResult Create()
        {
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "id", "nome");
            ViewData["IdFarmaceutico"] = new SelectList(_context.Farmaceuticos, "id", "nome");
            ViewData["IdProduto"] = new SelectList(_context.Produtos, "id", "nome");
            return View();
        }

        // POST: Vendas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,IdFarmaceutico,IdProduto,IdCliente,qntd,total")] Venda venda)
        {
            if (ModelState.IsValid)
            {
                Produto produto = _context.Produtos.Find(venda.IdProduto);
                produto.estoque = produto.estoque - venda.qntd;
                venda.total = venda.qntd * produto.valor;
                _context.Update(produto);

               

                _context.Add(venda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "id", "nome", venda.IdCliente);
            ViewData["IdFarmaceutico"] = new SelectList(_context.Farmaceuticos, "id", "nome", venda.IdFarmaceutico);
            ViewData["IdProduto"] = new SelectList(_context.Produtos, "id", "nome", venda.IdProduto);
            return View(venda);
        }

        // GET: Vendas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas.FindAsync(id);
            if (venda == null)
            {
                return NotFound();
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "id", "nome", venda.IdCliente);
            ViewData["IdFarmaceutico"] = new SelectList(_context.Farmaceuticos, "id", "nome", venda.IdFarmaceutico);
            ViewData["IdProduto"] = new SelectList(_context.Produtos, "id", "nome", venda.IdProduto);
            return View(venda);
        }

        // POST: Vendas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,IdFarmaceutico,IdProduto,IdCliente,qntd,total")] Venda venda)
        {
            if (id != venda.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaExists(venda.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.Clientes, "id", "nome", venda.IdCliente);
            ViewData["IdFarmaceutico"] = new SelectList(_context.Farmaceuticos, "id", "nome", venda.IdFarmaceutico);
            ViewData["IdProduto"] = new SelectList(_context.Produtos, "id", "nome", venda.IdProduto);
            return View(venda);
        }

        // GET: Vendas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venda = await _context.Vendas
                .Include(v => v.cliente)
                .Include(v => v.farmaceutico)
                .Include(v => v.produto)
                .FirstOrDefaultAsync(m => m.id == id);
            if (venda == null)
            {
                return NotFound();
            }

            return View(venda);
        }

        // POST: Vendas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venda = await _context.Vendas.FindAsync(id);
            if (venda != null)
            {
                _context.Vendas.Remove(venda);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaExists(int id)
        {
            return _context.Vendas.Any(e => e.id == id);
        }
    }
}

Views/Vendas/Create.cshtml
@model Dez.Models.Venda

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Nova Venda</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdFarmaceutico" class="control-label"></label>
                <select asp-for="IdFarmaceutico" class="form-control" asp-items="ViewBag.IdFarmaceutico"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdProduto" class="control-label"></label>
                <select asp-for="IdProduto" class="form-control" asp-items="ViewBag.IdProduto"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <select asp-for="IdCliente" class="form-control" asp-items="ViewBag.IdCliente"></select>
            </div>
            <div class="form-group">
                <label asp-for="qntd" class="control-label"></label>
                <input asp-for="qntd" class="form-control" />
                <span asp-validation-for="qntd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="total" class="control-label"></label>
                <input asp-for="total" class="form-control" />
                <span asp-validation-for="total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Vendas/Delete.cshtml
@model Dez.Models.Venda

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Excluir Venda</h1>

<h3>Você tem certeza que deseja excluir esta Venda??</h3>
<div>
    <h4>Venda</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.farmaceutico)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.farmaceutico.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.produto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.produto.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cliente.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.qntd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.qntd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.total)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

Views/Vendas/Details.cshtml
@model Dez.Models.Venda

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Informações da Venda</h1>

<div>
    <h4>Venda</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.farmaceutico)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.farmaceutico.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.produto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.produto.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cliente.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.qntd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.qntd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.total)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Vendas/Edit.cshtml
@model Dez.Models.Venda

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Informações</h2>
<h3>Da</h3>
<h4>Venda</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="IdFarmaceutico" class="control-label"></label>
                <select asp-for="IdFarmaceutico" class="form-control" asp-items="ViewBag.IdFarmaceutico"></select>
                <span asp-validation-for="IdFarmaceutico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProduto" class="control-label"></label>
                <select asp-for="IdProduto" class="form-control" asp-items="ViewBag.IdProduto"></select>
                <span asp-validation-for="IdProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <select asp-for="IdCliente" class="form-control" asp-items="ViewBag.IdCliente"></select>
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="qntd" class="control-label"></label>
                <input asp-for="qntd" class="form-control" />
                <span asp-validation-for="qntd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="total" class="control-label"></label>
                <input asp-for="total" class="form-control" />
                <span asp-validation-for="total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Vendas/Index.cshtml
@model IEnumerable<Dez.Models.Venda>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Vendas</h1>

<p>
    <a asp-action="Create">Nova venda</a>
    <a asp-area="" asp-controller="Consulta" asp-action="VndC">Listagem por remédio</a>
    <a asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.farmaceutico)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.produto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.qntd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.total)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.farmaceutico.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.produto.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cliente.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.qntd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.total)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>