Models/Cliente.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Dez.Models
{
    [Table("Clientes")]
    public class Cliente
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = " ID: ")]
        public int id { get; set; }

        [Required(ErrorMessage = "Campo nome Obrigatório...")]
        [StringLength(50)]
        [Display(Name = " Nome: ")]
        public string nome { get; set; }

        [Required(ErrorMessage = "Campo CPF Obrigatório...")]
        [StringLength(11)]
        [Display(Name = " CPF: ")]
        public string cpf { get; set; }

        [Required(ErrorMessage = "Campo endereço Obrigatório...")]
        [StringLength(100)]
        [Display(Name = " Endereço: ")]
        public string endereco { get; set; }
    }
}

Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dez.Models;
using Microsoft.AspNetCore.Authorization;

namespace Dez.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private readonly Contexto _context;

        public ClientesController(Contexto context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nome,cpf,endereco")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nome,cpf,endereco")] Cliente cliente)
        {
            if (id != cliente.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.id == id);
        }
    }
}

Controllers/DadosController.cs
using Dez.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dez.Controllers
{
    public class DadosController : Controller
    {
        private readonly Contexto contexto;
        
        public DadosController (Contexto context)
        {
            contexto = context;

        }
        public IActionResult Cliente()
        {

            Random randNum = new Random();

            string[] Nome1 = { "Ricardo", "Alberto", "Lucas", "Eduardo", "Matheus" };
            string[] Nome2 = { "Nathalia", "Isadora", "Maria Eduarda", "Marie", "Paula" };
            string[] Cpf1 = { "038819470", "408717590", "368023130", "030260939", "36867169" };
            string[] Cpf2 = { "592043300", "160259360", "227270670", "659356540", "23048180" };
            string[] Cid1 = { "Assis", "Maracai", "Candido-Mota", "Florinea", "Tarumã" };
            string[] Cid2 = { "Londrina", "Marilia", "Garça", "Pedrinhas", "Cruzalia" };

            for (int i = 0; i < 10; i++)
            {
                Cliente cliente = new Cliente();
                cliente.nome = (i % 2 == 0) ? Nome1[i / 2] : Nome2[i / 2];
                cliente.cpf = (i % 2 == 0) ? Cpf1[i / 2] : Cpf2[i / 2];
                cliente.endereco = (i % 2 == 0) ? Cid1[i / 2] : Cid2[i / 2];
                contexto.Clientes.Add(cliente);

            }
            contexto.SaveChanges();

            return View(contexto.Clientes.OrderBy(o => o.nome).ToList());
        }

        public IActionResult Farmaceutico()
        {
            Random randNum = new Random();

            string[] Nome1 = { "Almir", "Matheus", "Rodolfo", "Jordan", "Geovani" };
            string[] Nome2 = { "Renata", "Claudete", "Heloisa", "Maria Augusta", "Mariana" };
            string[] Cpf1 = { "038819470", "408717590", "368023130", "030260939", "36867169" };
            string[] Cpf2 = { "592043300", "160259360", "227270670", "659356540", "23048180" };
            //string[] Cid1 = { "Assis", "Maracai", "Candido-Mota", "Florinea", "Tarumã" };
            //string[] Cid2 = { "Londrina", "Marilia", "Garça", "Pedrinhas", "Cruzalia" };

            for (int i = 0; i < 10; i++)
            {
                Farmaceutico farmaceutico = new Farmaceutico();
                farmaceutico.nome = (i % 2 == 0) ? Nome1[i / 2] : Nome2[i / 2];
                farmaceutico.cpf = (i % 2 == 0) ? Cpf1[i / 2] : Cpf2[i / 2];
                contexto.Farmaceuticos.Add(farmaceutico);

            }
            contexto.SaveChanges();

            return View(contexto.Farmaceuticos.OrderBy(o => o.nome).ToList());
        }

    }
}

Views/Clientes/Create.cshtml
@model Dez.Models.Cliente

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Novo Cliente</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
                <span asp-validation-for="endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Clientes/Delete.cshtml
@model Dez.Models.Cliente

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Excluir Cliente</h1>

<h3>Você tem certeza que deseja excluir este cliente?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cpf)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.endereco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.endereco)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

Views/Clientes/Details.cshtml
@model Dez.Models.Cliente

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Informações do Cliente</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.cpf)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.cpf)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.endereco)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.endereco)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Editar</a> |
    <a asp-action="Index">Voltar</a>
</div>
</div>

Views/Clientes/Edit.cshtml
@model Dez.Models.Cliente

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Informações</h2>
<h3>Do</h3>
<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="nome" class="control-label"></label>
                <input asp-for="nome" class="form-control" />
                <span asp-validation-for="nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
                <span asp-validation-for="endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Clientes/Index.cshtml
@model IEnumerable<Dez.Models.Cliente>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Create">Novo Cliente</a>
    <a asp-area="" asp-controller="Dados" asp-action="Cliente">Gerar Cliente</a>
    <a asp-area="" asp-controller="Home" asp-action="Index">Voltar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.endereco)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.endereco)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>